### PR TITLE
simple illustration of Optimus flow

### PR DESCRIPTION
**Pull request by schimmy**
I'm not super happy with the image, but we should have _something_ visual I think.
Thoughts? Replacements?

### CODE REVIEW

**Comment by azylman** [comment]
I'm not convinced that this is more useful than several good examples...

**Comment by schimmy** [comment]
Still planning on adding more examples! But I think a visual representation in some way is necessary... Right now this is very text-heavy, and there's no way to visually grok how things will hook together

**Comment by azylman** [comment]
@schimmy I'm gonna close this since the proposal wasn't accepted, and I'm still not convinced this diagram is useful. Let me know if you want to talk about this more!

**Comment by schimmy** [comment]
Yeah, fine to close. However I do think we need to help the more visual learners out there: http://blog.prezi.com/latest/2015/7/6/the-four-different-types-of-learners-and-what-they-mean-to-your-presentations-infographic
Currently this documentation is very heavily useful for people who learn by reading, which is I think your personal style, but not great for visual learners! So perhaps keep thinking about visual ways we can help show off Optimus - I'll want to do something before I write that blog post...

**Pull request closed without merging**
